### ISSUE TITLE
IE 11 support

### ISSUE THREAD

**Issue by NickolayBauer** [Rundik/vue-zoom-on-hover#3]
Hey guys

We love your library, but we have a responsibility to maintain Ie11.

There is an arrow function in one of the places in your code.
Please rewrite this function so that Ie11 does not break

thank
![image](https://user-images.githubusercontent.com/35115545/92922190-17a41380-f43e-11ea-81af-ee21c821d4be.png)
![image](https://user-images.githubusercontent.com/35115545/92922201-1bd03100-f43e-11ea-8a26-1b224ea304e4.png)
![image](https://user-images.githubusercontent.com/35115545/92922216-212d7b80-f43e-11ea-9096-9ac7536bafd8.png)

**Comment by Rundik** [comment]
Hi, I'll take a look at this this weekend, thanks for reporting

**Comment by MrNightingale** [comment]
@Rundik hi, any updates? I've also just found that it's not working.

**Comment by Rundik** [comment]
It should work now and in the demo as well
